from abc import ABC, abstractmethod
from datetime import datetime
from typing import Optional, List
import os
import polars as pl
from backend.app.options.data.types import IVSnapshot
from backend.app.options.data.providers.base import IVProvider
from backend.app.options.data.providers.mock import MockIVProvider

class IVStore(ABC):
    @abstractmethod
    def get_iv(self, ticker: str, timestamp: datetime, dte: int) -> Optional[IVSnapshot]:
        pass

class ProviderIVStore(IVStore):
    def __init__(self, provider: IVProvider):
        self.provider = provider

    def get_iv(self, ticker: str, timestamp: datetime, dte: int) -> Optional[IVSnapshot]:
        return self.provider.get_iv(ticker, timestamp, dte)

class ParquetIVStore(IVStore):
    def __init__(self, data_dir: str = "backend/data/options/iv"):
        self.data_dir = data_dir
        self.cache = {} # ticker -> DataFrame

    def _load_ticker(self, ticker: str):
        if ticker in self.cache:
            return self.cache[ticker]

        path = os.path.join(self.data_dir, f"{ticker}.parquet")
        if not os.path.exists(path):
            return None

        # We assume schema: timestamp, dte, atm_iv, iv_rank, iv_percentile
        df = pl.read_parquet(path)
        # Ensure sorted
        df = df.sort("timestamp")
        self.cache[ticker] = df
        return df

    def get_iv(self, ticker: str, timestamp: datetime, dte: int) -> Optional[IVSnapshot]:
        df = self._load_ticker(ticker)
        if df is None:
            return None

        # Find closest timestamp
        # Filter by DTE bucket? Usually we store fixed DTEs or interpolate.
        # Assuming we store multiple DTEs, we filter by DTE first.

        # Simple implementation: Exact DTE match or closest?
        # Let's assume the parquet has specific DTE columns or rows.
        # If rows: filter dte.

        # Let's assume rows.
        # Filter for DTE +/- 2 days?
        # For now, let's assume the parquet has exact DTEs (e.g. 30, 7) generated by ingest.
        # If not, we might fail.

        subset = df.filter(pl.col("dte") == dte)
        if subset.height == 0:
            return None

        # AsOf join or nearest?
        # Polars join_asof is efficient.

        target_df = pl.DataFrame({"timestamp": [timestamp]}).select(pl.col("timestamp").cast(pl.Datetime))

        # Ensure subset is sorted by timestamp
        subset = subset.sort("timestamp")

        # Preserve source timestamp
        subset = subset.with_columns(pl.col("timestamp").alias("data_timestamp"))

        # join_asof
        try:
            res = target_df.join_asof(subset, on="timestamp", strategy="backward", tolerance="1d")
        except Exception:
             # Tolerance syntax might vary or fail if types mismatch
             return None

        if res["atm_iv"].null_count() > 0:
            return None

        row = res.row(0, named=True)
        if row["atm_iv"] is None:
            return None

        return IVSnapshot(
            ticker=ticker,
            timestamp=row["data_timestamp"],
            dte=row["dte"],
            atm_iv=row["atm_iv"],
            iv_rank=row["iv_rank"],
            iv_percentile=row["iv_percentile"],
            metadata={"source": "parquet"}
        )

def get_iv_store(mode: str = "provider", provider: IVProvider = None) -> IVStore:
    if mode == "parquet":
        return ParquetIVStore()
    else:
        return ProviderIVStore(provider or MockIVProvider())
