from __future__ import annotations

import json
import shutil
import sqlite3
from pathlib import Path
from typing import Any


REQUIRED_ARTIFACT_FILES = {
    "weights.safetensors",
    "model_config.json",
    "feature_schema.json",
    "metrics.json",
    "calibration.json",
    "drift_baseline.json",
    "README_model_card.md",
}


class ModelRegistryStore:
    def __init__(self, db_path: Path, model_root: Path):
        self.db_path = db_path
        self.model_root = model_root
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self.model_root.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _conn(self) -> sqlite3.Connection:
        return sqlite3.connect(self.db_path)

    def _init_db(self) -> None:
        with self._conn() as conn:
            conn.executescript(
                """
                create table if not exists models(
                    model_name text primary key,
                    created_at text default current_timestamp
                );
                create table if not exists versions(
                    model_name text,
                    version text,
                    sha256 text,
                    created_at text default current_timestamp,
                    status text,
                    metrics_json text,
                    config_json text,
                    data_lineage_json text,
                    primary key(model_name, version)
                );
                create table if not exists aliases(
                    model_name text,
                    alias text,
                    version text,
                    primary key(model_name, alias)
                );
                """
            )

    def _validate_contract(self, version_dir: Path) -> None:
        missing = sorted(f for f in REQUIRED_ARTIFACT_FILES if not (version_dir / f).exists())
        if missing:
            raise ValueError(f"artifact contract missing files: {missing}")

    def publish_version(
        self,
        model_name: str,
        version: str,
        sha256: str,
        metrics: dict[str, Any],
        config: dict[str, Any],
        data_lineage: dict[str, Any],
        status: str = "staging",
    ) -> Path:
        version_dir = self.model_root / model_name / version
        version_dir.mkdir(parents=True, exist_ok=True)
        for name, payload in {
            "metrics.json": metrics,
            "model_config.json": config,
            "feature_schema.json": data_lineage.get("feature_schema", {}),
            "calibration.json": data_lineage.get("calibration", {"calibration_score": 0.5}),
            "drift_baseline.json": data_lineage.get("drift_baseline", {"mean": 0.0, "std": 1.0}),
        }.items():
            (version_dir / name).write_text(json.dumps(payload, sort_keys=True, indent=2), encoding="utf-8")
        (version_dir / "weights.safetensors").write_bytes(b"stub-weights")
        (version_dir / "README_model_card.md").write_text(
            f"# {model_name}:{version}\n\nAutogenerated model card.\n", encoding="utf-8"
        )
        self._validate_contract(version_dir)
        self._upsert_version(model_name, version, sha256, status, metrics, config, data_lineage)
        return version_dir

    def publish_artifact_directory(
        self,
        model_name: str,
        version: str,
        artifact_dir: Path,
        sha256: str,
        metrics: dict[str, Any],
        config: dict[str, Any],
        data_lineage: dict[str, Any],
        status: str = "staging",
    ) -> Path:
        destination = self.model_root / model_name / version
        destination.mkdir(parents=True, exist_ok=True)
        for item in artifact_dir.iterdir():
            if item.is_file():
                shutil.copy2(item, destination / item.name)
        self._validate_contract(destination)
        self._upsert_version(model_name, version, sha256, status, metrics, config, data_lineage)
        return destination

    def _upsert_version(
        self,
        model_name: str,
        version: str,
        sha256: str,
        status: str,
        metrics: dict[str, Any],
        config: dict[str, Any],
        data_lineage: dict[str, Any],
    ) -> None:
        with self._conn() as conn:
            conn.execute("insert or ignore into models(model_name) values (?)", (model_name,))
            conn.execute(
                """
                insert or replace into versions(model_name, version, sha256, status, metrics_json, config_json, data_lineage_json)
                values(?,?,?,?,?,?,?)
                """,
                (
                    model_name,
                    version,
                    sha256,
                    status,
                    json.dumps(metrics, sort_keys=True),
                    json.dumps(config, sort_keys=True),
                    json.dumps(data_lineage, sort_keys=True),
                ),
            )

    def set_alias(self, model_name: str, alias: str, version: str) -> None:
        if alias not in {"staging", "prod", "canary"}:
            raise ValueError(f"invalid alias {alias}")
        with self._conn() as conn:
            conn.execute(
                "insert or replace into aliases(model_name, alias, version) values(?,?,?)",
                (model_name, alias, version),
            )

    def resolve_alias(self, model_name: str, alias: str = "prod") -> str | None:
        with self._conn() as conn:
            row = conn.execute(
                "select version from aliases where model_name = ? and alias = ?",
                (model_name, alias),
            ).fetchone()
        return row[0] if row else None
